### ISSUE TITLE
Packaged version

### ISSUE THREAD

**Issue by smariel** [mofirouz/iTunesPlaylistTrackSyncer#2]
Hi,
I'm very interested in this script. But I was just wondering, is there any way I can find or make a "packaged" application for macOS that do not require me to install Go and the other dependencies in instal.sh ?

**Comment by mofirouz** [comment]
This isn't a script - it's a fully fledged binary. Once you build the binary, you can copy it to other macOS machine without the need to download the dependencies mentioned in `install.sh` file as they'll be statically linked within the binary.
